





POST http://localhost:8090/api/collections/users/auth-with-password
content-type: application/json

{"identity":"test@test.com","password":"pass"}

###
@token = xxx

GET http://localhost:8090/api/v1/hello/1
Authorization:  {{token}}



###

GET http://localhost:8090/api/v2/hello
Authorization:  {{token}}

###
GET http://localhost:8090/api/v1/hello
Authorization:  {{token}}





###

POST http://localhost:8090/api/v1/add
content-type: application/json
Authorization:  {{token}}

{"name":"Joe","email":"joe@labstack"}
